## Label Encoding

### Label encoding and ordinal encoding are two techniques used to encode categorical data as numerical data 
### Label encoding involves assigning a unique numerical label to eaach categorical in the variables.

In [6]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()

In [7]:
dataset = pd.DataFrame({
    'color': ['red','orange','blue','yellow','yellow','red','blue']
})

In [8]:
lbl_encoder.fit_transform(dataset[['color']])

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 1, 0, 3, 3, 2, 0])

In [10]:
lbl_encoder.transform([['red']])

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([2])

## Ordinal Encoding

### It is used to encode categorical data that have an intrinsic order or ranking. In this technique, each category is assigned a numerical valuebaseed on its position in the order. 

In [11]:
## Ordinal Encoding
from sklearn.preprocessing import OrdinalEncoder

In [12]:
dataset = pd.DataFrame({
    'size': ['small','medium', 'large','large','medium','small']
})

In [13]:
dataset

size
0   small
1  medium
2   large
3   large
4  medium
5   small

In [14]:
## Create an instance of OrdinalEncoder and then fit_transform
encoder=OrdinalEncoder(categories=[['small','medium','large']])


In [15]:
encoder.fit_transform(dataset[['size']])

array([[0.],
       [1.],
       [2.],
       [2.],
       [1.],
       [0.]])